blank_issues_enabled: true
contact_links:
  - name: QQ群反馈(Tencent QQ group feedback)
    url: https://jq.qq.com/?_wv=1027&k=eW9a2PnI
    about: 如果情况紧急或者只是想闲聊，您可以加入QQ群来反馈/聊天(If you want to feed back urgent bugs or just want to chat, you can join the QQ group to feed back / chat)
